### ISSUE TITLE
[INTEGRATION] Treedefi

### ISSUE THREAD

**Issue by jmgomezpoveda** [wallet-now/wallet-now#30]
- Did you search our open issues for this protocol already? yes

**Fill the following to speed-up integration**
 - Protocol: Treedefi
 - Website: https://app.treedefi.com/

**Comment by wallet-now** [comment]
We have just deployed support for TreeDefi on WalletNow.net. Enjoy ;)

**Comment by wallet-now** [comment]
https://twitter.com/WalletNow/status/1417604487171264522
