### ISSUE TITLE
[INTEGRATION] PancakeHunny

### ISSUE THREAD

**Issue by pancakehunny** [wallet-now/wallet-now#39]
MANDATORY:
- Did you search our open issues for this protocol already? [yes]

Fill the following to speed-up integration
- Protocol: PancakeHunny
- Website: https://pancakehunny.finance

OPTIONAL - Additional context
- Please refer to the attached PDF. [PancakeHunny_Hives_Contract.pdf](https://github.com/wallet-now/wallet-now/files/7128739/PancakeHunny_Hives_Contract.pdf)
- Sample wallet address with investments locked on that protocol: 0xe5F7E3DD9A5612EcCb228392F47b7Ddba8cE4F1a

**Comment by wallet-now** [comment]
Launched on Sep 16th
https://twitter.com/PancakeHunny/status/1438508913935065089
