### ISSUE TITLE
[FEATURE] IL notifications

### ISSUE THREAD

**Issue by wallet-now** [wallet-now/wallet-now#40]
Our users could benefit from IL notifications (Active Monitoring) on at least two use-cases:
1. Know when the IL gets too high, past a configurable threshold, so they can get out on time
2. Know when the IL returned to an acceptable level, so it is now a good time to break the LP

**Comment by Whatnam8** [comment]
Just going to throw ideas out and please see what you think makes sense.

I would also suggest if this feature gets implemented it could also go on some of the existing commands like /snapshot or maybe even new commands made like /IL that will tell you all LP's, deposit amount (token A:token B)/current amount (token A:token B), value and IL%.  Just spitballing ideas if any of them seem good.  

Also for stat heavy people that want to see their stuff all the time one possibility set up an automatic snapshot on a time scale like every hour etc. as an option, maybe an extensive summary that could combine /snapshot with /pending 
To have it in one big block like a daily summary.

Thanks for listening!

**Comment by Whatnam8** [comment]
Another idea for an IL alert is to be able to set an alert to go out each time IL moves to a new milestone.  If you wanted to know each time it hit another (1/2)% or whatever the user determines did example .5% alerts,  1.0% alerts, 1.5% alerts, back to 1.0%.  Just ideas

**Comment by Whatnam8** [comment]
Just another features I found nice to know but not need to know is how many days we've been in a vault, farm etc. and see how it's performing relatively per day

**Comment by wallet-now** [comment]
We are migrating from Github issues to a feature voting platform, please vote and comment here: https://61649d439d039.sleekplan.app/feedback/6500
