### ISSUE TITLE
Sorting in address overview causes duplication of vault entries

### ISSUE THREAD

**Issue by 623134636b3768756e643372** [wallet-now/wallet-now#41]
Sorting by Name/Protocol/Value in the wallet overview causes custom vaults to duplicate. 

**To Reproduce**
0. Add custom vaults in settings 
1. Open address overview (home)
2. Click at any category (name/protocol/value) to sort by this category 

**Expected behavior**
Vaults and wallet entries being sorted by category.

**Screenshots**
![Screenshot_20210918-235600.jpg](https://user-images.githubusercontent.com/86501450/133909533-893100a5-f698-4e22-be51-90bff3fb3f9d.jpg)

**Smartphone:**
 - OS: Android 11
 - Browser: Firefox
 - Version: 92.1.1

**Comment by wallet-now** [comment]
We have fixed some issues which were causing this behavior. Can you please check if it solved for you as well?
Please re-open if necessary.
Thanks

**Comment by 623134636b3768756e643372** [comment]
issue is fixed, thank you
