### ISSUE TITLE
[BUG] Investments filtered based on your membership tier: 

### ISSUE THREAD

**Issue by Utone** [wallet-now/wallet-now#47]
**Describe the bug**
After adding custom vaults, profile loads as Free tier without showing the custom vaults
with notification 
Investments filtered based on your membership tier: XXX Vault

Refreshing lost all custom added vaults, (This might have been uBlock Origin related)
 pressing refresh on the page loads Gold tier and the vault will see if it happens again

**Expected behavior**
skipping the free tier, reload, losing vaults part to how it works after refresh now

**Screenshots**

**Desktop (please complete the following information):**
 - macOS BigSur
 - Browser: chrome latest
 - Wallet app: Metamask

**Smartphone (please complete the following information):**

**Additional context**
![Tier doesn't load](https://user-images.githubusercontent.com/5865016/135177970-8f44b053-f219-4a52-a835-e5c8344cf4f0.png)
![after creating new custom vault and going to Profile](https://user-images.githubusercontent.com/5865016/135177973-6fae0622-5b59-4a6c-9bef-f38734719d4f.png)
![Needs Refresh on page not in browser](https://user-images.githubusercontent.com/5865016/135177975-965bf8ad-b13d-4b2e-952a-bc85810d123c.png)

**Comment by Utone** [comment]
I just noticed this behavior returned after staking a tiny amount of WNOW-WBNB my Gold updated to Diamond, I staked all, and again same free tier and then noticed the balance
Your Portfolio
$111,961,299,456,309,390.00.  o-O/- lol 
![Screen Shot 2021-09-29 at 01 35 31AM](https://user-images.githubusercontent.com/5865016/135179547-4fe2f12d-39f3-450e-836b-9390bf76ee2e.png)

probably some phishing token I'm not seeing that triggers this, despite Net worth being more accurate...?

**Comment by Utone** [comment]
After some refreshing finally snaps out of Free mode into diamond but it should be Gold.
Now Balance is lower than actual
![Screen Shot 2021-09-29 at 01 50 40AM](https://user-images.githubusercontent.com/5865016/135180733-bf183573-e32d-4460-abe9-ec55162f2b13.png)

**Comment by Utone** [comment]
Telegram is also giving the free tier errors

**Comment by wallet-now** [comment]
As we talked on Telegram, the issue was caused by a flaky "Custom Vault".
Unfortunately custom vaults are "best effort" and sometimes they may cause issues with weird values. On those cases all we can do is removing the vault.

Please let us know if you face any additional issue
