### ISSUE TITLE
[BUG] Qubit supply vault not recognized

### ISSUE THREAD

**Issue by 623134636b3768756e643372** [wallet-now/wallet-now#52]
**Describe the bug**
The Qubit vault is not recognized after adding to custom vaults.

**Expected behavior**
Qubit  vault appearing in overview.

**Screenshots**
![image](https://user-images.githubusercontent.com/86501450/140771172-bb0a118c-1f0d-4497-88fb-89d7a1f60665.png)
Configuration in custom vault
![image](https://user-images.githubusercontent.com/86501450/140769728-ff25a23e-9048-4aba-881d-9154cd3a28cd.png)
Overview of wallet
![image](https://user-images.githubusercontent.com/86501450/140771526-7b72f549-3d48-4721-8040-14d9e92aaf79.png)
Deposit transaction

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi
 - Wallet app: Metamask

**Additional context**
Vault configuration:
- 0xf70314eb9c7fe7d88e6af5aa7f898b3a162dcd48
- Qubit Finance
- https://qbt.fi/app
- 0x17b7163cf1dbd286e262ddc68b553d899b93f526
- accruedQubit

Also no effect when using contract 0xcD2CD343CFbe284220677C78A08B1648bFa39865 where QBT were deposited

**Comment by wallet-now** [comment]
Qubit uses a smart contract architecture which is very different from most regular farms... You can track some of it by adding 0xf70314eb9c7fe7d88e6af5aa7f898b3a162dcd48 as a vault, but then all markets will be mixed together.

The only alternative is to integrate the protocol natively. If we get some collaboration from the Qubit, we can integrate fairly quickly
