### ISSUE TITLE
[BUG] WNOW token not recognized on CZodiac

### ISSUE THREAD

**Issue by anhess** [wallet-now/wallet-now#54]
**Describe the bug**
I have my WNOW token in CZodiac farms and WalletNow doesn‘t recognize them.

**To Reproduce**
1. Open up a WNOW farm on CZodiac
2. Click on plan on WalletNow
3. Balance shown is zero

**Expected behavior**
On your plan page you state, that the WNOW can be put into Liquidity Pools and even in farms.

**Screenshots**
![IMG_0489](https://user-images.githubusercontent.com/65921412/156912788-4c09938e-103d-43e6-81b4-a80bdf8f2cef.png)

**Desktop (please complete the following information):**
 - all browsers

**Smartphone (please complete the following information):**
 - all devices

**Additional context**

**Comment by wallet-now** [comment]
Thanks for the report. CZodiac was not configured correctly, and this is fixed now. Please let us know if you still face any problems.
