### ISSUE TITLE
[BUG] No full Belt.fi support

### ISSUE THREAD

**Issue by anhess** [wallet-now/wallet-now#56]
**Describe the bug**
I invest in a single BELT staking vault on Belt.fi and even so, Belt.fi is listed as a supported protocol, I have to add it manually via a custom vault.

**To Reproduce**
1. Invest into the single BELT vault on BSC (address: 0x1794bb186c15fddbf4aac4a3b0e2f40659e9b841)
2. Investment isn‘t seen on WalletNow until added as a custom vault

**Expected behavior**
No need to add it as a custom vault.

**Screenshots**
![IMG_0496](https://user-images.githubusercontent.com/65921412/156945269-5c9a294f-3af2-416f-8b21-3912dba216a4.jpeg)

**Desktop (please complete the following information):**
 - all browsers

**Smartphone (please complete the following information):**
 - all devices

**Additional context**

**Comment by wallet-now** [comment]
Thanks for the report. sBELT was missing on the list and was added now. As many other BELT tokens, it will show up on your wallet, with the proper price already accounting for your profits.
